version: '3'
services:
  mongodb:
    image: mongo:6-jammy
    container_name: content-moderation
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - '27017:27017'
    volumes:
      - ./dbdata:/data/db # Persist MongoDB data